KEY_FONT = "font"
KEY_FONT_ENCODING = "encoding"
KEY_FONT_SIZE = "size"
KEY_FONT_TYPE = "type"
KEY_FONT_TYPE_DEFAULT = "default"
KEY_FONT_TYPE_SYSTEM = "system"
KEY_FONT_TYPE_BYPATH = "bypath"
KEY_FONT_NAME = "name"
KEY_FONT_PATH = "name"
KEY_FONT_SIZEMODE = "sizemode"
KEY_FONT_SIZEMODE_STRETCH = "stretch"
KEY_FONT_SIZEMODE_FIXED = "fixed"
KEY_FONT_SIZEMODE_AUTOSIZE = "autosize"
KEY_SYMBOLS = "symbols"
KEY_SYMBOLS_TYPE = "type"
KEY_SYMBOLS_TYPE_RANGE = "range"
KEY_SYMBOLS_TYPE_LIST = "list"
KEY_SYMBOLS_TYPE_RANGE_START = "start"
KEY_SYMBOLS_TYPE_RANGE_END = "end"
KEY_SYMBOLS_TYPE_LIST_LIST = "list"
KEY_SYMBOLSIZE = "symbolSize"
KEY_SYMBOLSIZE_W = "width"
KEY_SYMBOLSIZE_H = "height"
KEY_FONT_POSITIONING = "positioningmode"
KEY_FONT_POSITIONING_CENTERED = "centered"
KEY_FONT_POSITIONING_CENTERED_BOTTOM = "centered_bottom"
KEY_FONT_POSITIONING_ZERO = "zero"

allowed_fontpositioning = [
    KEY_FONT_POSITIONING_CENTERED,
    KEY_FONT_POSITIONING_CENTERED_BOTTOM,
    KEY_FONT_POSITIONING_ZERO
]

allowed_fonttypes = [
    KEY_FONT_TYPE_DEFAULT,
    KEY_FONT_TYPE_SYSTEM,
    KEY_FONT_TYPE_BYPATH,
]

allowed_fontmodes = [
    KEY_FONT_SIZEMODE_FIXED,
    KEY_FONT_SIZEMODE_STRETCH,
    KEY_FONT_SIZEMODE_AUTOSIZE
]

allowed_symbolstypes = [
    KEY_SYMBOLS_TYPE_RANGE,
    KEY_SYMBOLS_TYPE_LIST
]