KEY_ACTION = "action"
KEY_ACTION_TYPE = "actionType"
KEY_ACTION_TYPE_FONTTEST = "fontTest"
KEY_ACTION_TYPE_SAVE = "save"

KEY_ACTION_FONTSOURCE = "fontSource"
KEY_ACTION_FONTSOURCE_TI = "ti"
KEY_ACTION_FONTSOURCE_IMAGES = "images"
KEY_ACTION_FONTSOURCE_BIN = "bin"
KEY_ACTION_FONTSOURCE_HEADER = "header"
KEY_ACTION_FONTSOURCE_NEW = "new"

KEY_ACTION_FONTPATH = "fontPath"

KEY_ACTION_SAVEAS = "saveAs"
KEY_ACTION_SAVEAS_BINARY = "bin"
KEY_ACTION_SAVEAS_TI = "ti"
KEY_ACTION_SAVEAS_IMAGES = "images"
KEY_ACTION_SAVEAS_HEADER = "header"

KEY_ACTION_FONTTESTSTRING = "fontTestString"

KEY_ACTION_SAVEFONTENCODING = "saveFontEncoding"
KEY_ACTION_SAVEFONTENCODING_RAW = "raw"
KEY_ACTION_SAVEFONTENCODING_RLE = "rle"
KEY_ACTION_SAVEFONTENCODING_RLESB = "rle_sb"

KEY_ACTION_OUT_HEADER = "outputHeaderFile"
KEY_ACTION_OUT_BINARY = "outputBinaryFile"
KEY_ACTION_OUT_TEST = "outputFontTestOutFile"

KEY_NFP = "newFontParameters"
KEY_NFP_ENCODING = "encoding"
KEY_NFP_SIZE = "fontSize"
KEY_NFP_TYPE = "fontType"
KEY_NFP_TYPE_DEFAULT = "default"
KEY_NFP_TYPE_TTF = "ttf"
KEY_NFP_TYPE_BITMAP = "bitmap"
KEY_NFP_NAME = "name"
KEY_NFP_PATH = "name"
KEY_NFP_SIZEMODE = "sizeMode"
KEY_NFP_SIZEMODE_STRETCH = "stretch"
KEY_NFP_SIZEMODE_FIXED = "fixed"
KEY_NFP_SIZEMODE_AUTOSIZE = "autosize"
KEY_NFP_POSITIONING = "positioningMode"
KEY_NFP_POSITIONING_CENTERED = "centered"
KEY_NFP_POSITIONING_CENTERED_BOTTOM = "centered_bottom"
KEY_NFP_POSITIONING_ZERO = "zero"

KEY_NFP_SS = "symbolSequence"
KEY_NFP_SS_TYPE = "ssType"
KEY_NFP_SS_NULLCHAR = "nullChar"
KEY_NFP_SS_TYPE_RANGE = "range"
KEY_NFP_SS_TYPE_LIST = "list"
KEY_NFP_SS_TYPE_RANGE_START = "start"
KEY_NFP_SS_TYPE_RANGE_END = "end"
KEY_NFP_SS_TYPE_LIST_LIST = "list"

KEY_NFP_SYMBOLSIZE = "symbolSize"
KEY_NFP_SYMBOLSIZE_W = "width"
KEY_NFP_SYMBOLSIZE_H = "height"

KEY_NFP_OUTPUT = "output"
KEY_NFP_OUTPUT_OUTDIR = "outdir"
KEY_NFP_OUTPUT_CACHEFN = "fontCacheFile"
KEY_NFP_OUTPUT_FILES = "files"

KEY_NFP_OUTPUT_FILES_SAVE = "saveFiles"
KEY_NFP_OUTPUT_FILES_FNF = "filesNameFormat"

KEY_NFP_OUTPUT_TI = "totalImage"
KEY_NFP_OUTPUT_TI_SAVE = "saveTI"
KEY_NFP_OUTPUT_TI_NAME = "TIName"
KEY_NFP_OUTPUT_TI_IMAGESPERROW = "imagesPerRow"
KEY_NFP_OUTPUT_TI_SEPCOLOR = "separatorColor"

allowed_fontpositioning = [
    KEY_NFP_POSITIONING_CENTERED,
    KEY_NFP_POSITIONING_CENTERED_BOTTOM,
    KEY_NFP_POSITIONING_ZERO
]

allowed_fonttypes = [
    KEY_NFP_TYPE_DEFAULT,
    KEY_NFP_TYPE_TTF,
    KEY_NFP_TYPE_BITMAP,
]

allowed_fontmodes = [
    KEY_NFP_SIZEMODE_FIXED,
    KEY_NFP_SIZEMODE_STRETCH,
    KEY_NFP_SIZEMODE_AUTOSIZE
]

allowed_symbolstypes = [
    KEY_NFP_SS_TYPE_RANGE,
    KEY_NFP_SS_TYPE_LIST
]

allowed_actiontypes = [
    KEY_ACTION_TYPE_FONTTEST,
    KEY_ACTION_TYPE_SAVE
]

allowed_fontsources = [
    KEY_ACTION_FONTSOURCE_TI,
    KEY_ACTION_FONTSOURCE_IMAGES,
    KEY_ACTION_FONTSOURCE_BIN,
    KEY_ACTION_FONTSOURCE_HEADER,
    KEY_ACTION_FONTSOURCE_NEW,
]

allowed_saveAs = [
    KEY_ACTION_SAVEAS_BINARY,
    KEY_ACTION_SAVEAS_HEADER,
    KEY_ACTION_SAVEAS_TI,
    KEY_ACTION_SAVEAS_IMAGES
]

allowed_saveFontEncoding = [
    KEY_ACTION_SAVEFONTENCODING_RAW,
    KEY_ACTION_SAVEFONTENCODING_RLE,
    KEY_ACTION_SAVEFONTENCODING_RLESB
]